- NumPy - numerical operations
- Pandas - deal with data manipulation
- Matplotlib - plotting library
- Scikit-learn - machine learning
- Tensorflow or PyTorch - are frameworks for deep learning

## NumPy

- Numerical Python - Num Py
- gives us a fast data type - called Array or `ndarray` - N-Dimensional Array
- Numpy helps us do math on arrays
    - Data science and analytics?, how it helps?
    - Store data in arrays
    - Implement statistics or other operations
    - Matrix operations - can help in tables, ML and also DL
- numpy is one of the most fundamental libraries in python
- 
- there used to be a discussion on whether to put numpy inside of python by default
    - creators of python thought that would be too much code to handle
    - 
- [Learn Numpy from Documentation](https://numpy.org/doc/stable/user/absolute_beginners.html)

In [1]:
pip install numpy


[notice] A new release of pip is available: 26.0.1 -> 26.1.2
[notice] To update, run: pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.


- Everything we covered so far, was to teach you python and programming
    - is so that you can learn things on your own later
- 

## Arrays
- Array is a homogenous and linear data structure
    - homogenous - you save `only one type of data` elements inside
    - it has indices - we can use them to access data
    - Contigous blocks of memory - every element comes one after the other
        - Unlike lists, where every element is scattered through the memory
- if we already have lists in python, why do we need arrays?
    - Arrays are very **FAST** compared to list
        - reason is not just how numpy was created, but also the fact that we only store single type of data inside arrays
        - 
- Numpy arrays are better at numerical operation than python lists ---> because of **BROADCASTING**

In [2]:
import numpy as np

num_array = np.array(1)
print(num_array)
num_array

1


array(1)

In [3]:
nums_array = np.array(range(10))
print(type(nums_array))
print(nums_array)
nums_array

<class 'numpy.ndarray'>
[0 1 2 3 4 5 6 7 8 9]


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# homogenity of arrays

homo_array = np.array(['i', 9, 0.98, 'haho'])
homo_array

# dtype='<U32' ---> this data type says that --- this array won't be as fast
# array lose its special powers of speed and memory optimization
# this is worse than a list

array(['i', '9', '0.98', 'haho'], dtype='<U32')

In [7]:
nums_list = list(range(1,10))
nums_list

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [8]:
nums_list = [n*10 for n in nums_list]
nums_list

[10, 20, 30, 40, 50, 60, 70, 80, 90]

In [ ]:
nums_array*10

# no need for comprehension like list

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

- This is called BROADCASTING
    - one of the special things about Numpy
    - Broadcasting means taking an array and operating it with another
        - following a one to one operation
        - every element operated with another

- numpy lets us do numerical operations really well

List | Array
----|-----
store pointers(addresses of the data) | Store actual data
objects are scattered through the memory | are Contigous (one after the other)
CPU has to go to each object address to access data | CPU accesses base address and then adds e.g. 8 to that address to get the next element
Heterogenous, every object of different type | Homogenous, Multiple types are not allowed
every object has some extra baggage like data type information | dtype of an entire array is same
Broadcasting is not allowed | Broadcasting can be done

- you won't be able to notice too much difference until you have 1000s of elements to deal with
- until the data to deal with is huge, you will not notice how arrays are life savers

### Shapes and Dimensions

1D array :

2D array :

3D array :

...

### Exercise: (understand performance difference between the two)
1. Create a python List ---> `N = 10000` then `listname = list(range(N))`
2. Create an numpy array
3. We observe the size of both ---> use the `sys` module and `sys.getsizeof()`
4. Use time module to time the amount of time taken to do multiplication
    - `start_time = time.time() # current time`
    - your list *2 ---> execute this
    - end_time = time.time()
    - list_time = end_time - start_time ---> amount of time took for a list to multiply 2 with all the members
5. Repeat the step 4 with an array - But simply multiply the array with the list

If not much difference please increase `N` to 1000000000