### Arrays
- data structure given by Numpy
- better than lists at huge data
- 

### Array Properties
- what attributes numpy gives you for array object

- ndim - means Dimensions - the number of axis of an array - 
- shape - number of rows, number of columns
- size - number of elements inside
- dtype - the type of array or the elements inside are of which type

In [2]:
array1d = np.array([1, 2, 3, 4]) # 1D array

array1d.ndim

1

In [7]:
array2d = np.array([[1, 2, 3, 4],
                    [3, 4, 5, 6]])

array2d.ndim

2

In [10]:
array3d = np.array([[[1, 2, 3],[1, 2, 3]],
                    [[1, 2, 3],[1, 2, 3]]])

array3d.ndim

3

- inhomogenous shapes are not allowed for multi-dim array
- 

##### Broadcasting

In [1]:
import numpy as np

num_4 = np.array([1, 2, 3, 4])
num_3 = np.array([10, 10, 20])

(num_4 * 10) + 2

array([12, 22, 32, 42])

In [23]:
arr_table = np.array([[1, 2],
                      [1, 2],
                      [1, 2],
                      [1, 2],
                      [1, 2]])

print(arr_table.ndim)
print(arr_table.shape)
print(arr_table.size)
print(arr_table.dtype)

2
(5, 2)
10
int64


In [12]:
arr_table * 10

array([[10, 20],
       [10, 20],
       [10, 20],
       [10, 20],
       [10, 20]])

In [20]:
arr_table * [10, 100]

array([[ 10, 200],
       [ 10, 200],
       [ 10, 200],
       [ 10, 200],
       [ 10, 200]])

In [22]:
arr_table * [[10], [100], [1000], [10000], [100000]]

array([[    10,     20],
       [   100,    200],
       [  1000,   2000],
       [ 10000,  20000],
       [100000, 200000]])

### Creating an array
- ways to quickly create some arrays
- 

In [24]:
arr = np.arange(1, 10, 2)
arr

array([1, 3, 5, 7, 9])

In [29]:
np.zeros((3, 3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [27]:
np.ones((2, 2))

array([[1., 1.],
       [1., 1.]])

In [31]:
np.linspace(0, 10, 5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [56]:
np.random.seed(42)
print(np.random.randint(0,2))
print(np.random.randint(1, 10, 5))
np.random.randint(1, 9, (2, 3))

0
[4 8 5 7 3]


array([[7, 3, 3],
       [8, 5, 4]])

### Slicing and Indexing

### Important array methods

### Array Multiplication

### Aggregations and Boolean Masking