### Array Multiplication

Matrix multiplication is not regular multiplication:
- use the `@` operator like ---- A @ B
- use the `np.matmul(A, B)`

In [2]:
import numpy as np

In [3]:
A = np.random.randint(0,10,(2,2))
print(A)
B = np.random.randint(0,10,(2,2))
print(B)

A * B

[[4 3]
 [4 0]]
[[1 1]
 [3 4]]


array([[ 4,  3],
       [12,  0]])

In [4]:
A @ B

array([[13, 16],
       [ 4,  4]])

In [5]:
np.matmul(B, A)

array([[ 8,  3],
       [28,  9]])

### Aggregations
- Aggregations: - data and you summarize it
    - Sum
    - mean
    - min max
    - Standard Deviation
    - Variance
    - count
    - argmax argmin

- Aggregation along an AXIS
- `axis = 0` ===> down the ROWs --- (operate on Columns)
- `axis = 1` ===> across the COLUMNs --- (operate on Rows)

In [6]:
data = np.random.randint(0, 10, (2, 3))
print(data)

[[9 9 3]
 [0 0 1]]


In [7]:
print(data.sum()) # numpy array methods
print(sum(data)) # python way of data aggregation

print(data.mean())
print(data.std())
print(data.var())

print(data.min())
print(data.max())

22
[9 9 4]
3.6666666666666665
3.901566636906542
15.222222222222223
0
9


In [8]:
print(data.sum(axis= 0))
print(data.sum(axis= 1))

[9 9 4]
[21  1]


In [9]:
print(data.mean(axis= 0))
print(data.mean(axis= 1))

[4.5 4.5 2. ]
[7.         0.33333333]


### Boolean Masking - (Filtering)
- used to filter elements out
- 
- array[mask] ==== mask is a condition
- `array_name[<condition>]`

In [10]:
scores = np.random.randint(0, 101, 6)
scores

array([49, 78, 28, 88, 64, 51])

In [11]:
print(scores > 39)
print(scores[scores > 39])

[ True  True False  True  True  True]
[49 78 88 64 51]


In [12]:
age = np.array([5, 17, 24, 51, 23, 14, 8, 29, 33, 44, 10])
vote_age = age >= 18
age[vote_age]

array([24, 51, 23, 29, 33, 44])

In [13]:
voting_eligibility = np.where(age >= 18, 'Eligible', 'Not-Eligible')

In [14]:
list_zip = list(zip(age, voting_eligibility))

In [15]:
for age, voting_eligibility in list_zip:
    print(f'{age}: {voting_eligibility}!')

5: Not-Eligible!
17: Not-Eligible!
24: Eligible!
51: Eligible!
23: Eligible!
14: Not-Eligible!
8: Not-Eligible!
29: Eligible!
33: Eligible!
44: Eligible!
10: Not-Eligible!


In [16]:
age = np.array([5, 17, 24, 51, 23, 14, 8, 29, 33, 44, 10])
voting_eligibility = np.where(age >= 18, 'Eligible', 'Not-Eligible')

combined_array = np.column_stack((age, voting_eligibility))
print(combined_array)

[['5' 'Not-Eligible']
 ['17' 'Not-Eligible']
 ['24' 'Eligible']
 ['51' 'Eligible']
 ['23' 'Eligible']
 ['14' 'Not-Eligible']
 ['8' 'Not-Eligible']
 ['29' 'Eligible']
 ['33' 'Eligible']
 ['44' 'Eligible']
 ['10' 'Not-Eligible']]


---
BONUS PART

### Nested Loops

```python

for <variable> in <iterable>:
    print(<variables>)

In [ ]:
for i in range(5):
    print(i)

0
1
2
3
4


In [20]:
alist = [3, 5, 7, 9]
name = 'Alya'

for variable in name:
    print(variable)

A
l
y
a


- enumerate object is a sequence
- just like zip

- just like range - range can be type casted into a list
    - others cannot

- we run for loops on them - 

In [22]:
for i, j in enumerate(name):
    print(i, j)

0 A
1 l
2 y
3 a


In [23]:
for i in range(5):
    for j in range(5):
        print(i)

0
0
0
0
0
1
1
1
1
1
2
2
2
2
2
3
3
3
3
3
4
4
4
4
4


In [24]:
array2d = np.random.randint(0, 10, (2, 4))
array2d

array([[4, 6, 8, 4],
       [7, 6, 9, 7]])

In [26]:
for row in array2d:
    for value in row:
        print(value)

4
6
8
4
7
6
9
7


In [28]:
for row in array2d:
    for value in row:
        print(value, end='  ')
    print()

4  6  8  4  
7  6  9  7  


In [29]:
for i in range(len(array2d)):
    for j in range(len(array2d[i])):
        print(f'Row {i}, col {j}: {array2d[i][j]}')

Row 0, col 0: 4
Row 0, col 1: 6
Row 0, col 2: 8
Row 0, col 3: 4
Row 1, col 0: 7
Row 1, col 1: 6
Row 1, col 2: 9
Row 1, col 3: 7
